### ISSUE TITLE
Expose data stored in `Expect` as true public API

### ISSUE THREAD

**Issue by Veetaha** [rust-analyzer/expect-test#14]
As for now the `data: &'static str` property of `Expect` struct is marked as `doc(hidden)`, which means that it is intended to be private.

https://github.com/rust-analyzer/expect-test/blob/f0cd358a1c4bc876bb778d7b769e455052f6171f/src/lib.rs#L198-L205

However, I have a use case where I need to access the data of the snapshot from `expect` to do further assertions.
It is not possible to workaround this by storing the data in a separate variable:

```rust
let data = "...";
let expect = expect![[data]];
```

just because `expect!` macro accepts a `literal` token, not an `expr`.

I suggest exposing a public getter for `data`, @matklad wdyt?

**Comment by matklad** [comment]
sgtm! 

Let's expose

```rust
fn data(self) -> &str
```
