### ISSUE TITLE
"]]" inside an `expect` breaks updating

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-analyzer/expect-test#20]
The current code does a simple search for the character sequence `]]` to determine the end of an `expect![[` macro invocation. However, `expect` takes a string, and "]]" is perfectly valid as part of a string.

**Comment by matklad** [comment]
Yeah… we should’t be adding a real Rust parser here, but it makes sense to make heuristic more robust to the practical cases. Here, I think it makes sense to verify that symbols before `]]` are quote/hash and whotespace

**Comment by ecstatic-morse** [comment]
> we should’t be adding a real Rust parser here

@matklad Interesting. I thought this would be the solution. is this just to avoid the `syn` dependency? You could also go half way and write/steal a tokenizer for just string literals. I'll write the simple regex in the meantime. Maybe we can discuss on the PR.
