### ISSUE TITLE
`to_abs_ws_path` goes too far up

### ISSUE THREAD

**Issue by fasterthanlime** [rust-analyzer/expect-test#33]
Running RA tests from within a `rust-lang/rust` checkout fails, because `expect-test` climbs all the way up to `rust/Cargo.toml` instead of being happy with `rust/src/tools/rust-analyzer/Cargo.toml`, and then the paths are all wrong.

See https://github.com/rust-lang/rust/pull/99444#issuecomment-1188844202 for real-world details.

**Comment by fasterthanlime** [comment]
Relevant code:

https://github.com/rust-analyzer/expect-test/blob/21f04f35eb1d6d9dbcbd1f81a0a8c526432c5c0a/src/lib.rs#L644-L668

**Comment by fasterthanlime** [comment]
A clean fix for that would require https://github.com/rust-lang/cargo/issues/3946 to be tackled, but the workaround suggested in https://github.com/rust-lang/cargo/issues/3946#issuecomment-749645286 doesn't seem terrible to me:

```shell
$ pwd
/home/amos/bearcove/rust/src/tools/rust-analyzer/crates/ide/src/syntax_highlighting
$ cargo locate-project --workspace --message-format plain
/home/amos/bearcove/rust/src/tools/rust-analyzer/Cargo.toml
```

**Comment by flodiebold** [comment]
An alternative fix for our specific situation would be to simply set an environment variable (maybe named `CARGO_WORKSPACE`) from x.py and use that if present :thinking:

**Comment by Veykril** [comment]
That would also be a nice alternative, assuming the people responsible for `x.py` are fine with adding that

**Comment by fasterthanlime** [comment]
As another alternative, this hack doesn't involve calling out to cargo: https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993

The idea would be to create a `rust-analyzer/.cargo/config.toml` file with this:

```toml
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
```

Then the env var would be set when running `cargo test`.

**Comment by flodiebold** [comment]
Yeah, I like that a bit more than changing x.py since it will also work when you just run `cargo test` inside the rust-analyzer submodule.

**Comment by flodiebold** [comment]
... or we could merge #30, I guess? :thinking:

**Comment by fasterthanlime** [comment]
> ... or we could merge #30, I guess? 🤔

Mhh I don't love the adhoc-toml-parsing there, it'll fail for (admittedly fringe) cases like this:

```toml
workspace = { members = [
	"xtask/",
	"lib/*",
	"crates/*",
], exclude = [
	"crates/proc-macro-test/imp",
] }
```

**Comment by fasterthanlime** [comment]
> Mhh I don't love the adhoc-toml-parsing there

I'd like that PR more if it brought a real TOML parser with it but now _that's_ overkill, and that energy is better spent pushing for the cargo bug to be fixed instead imho.

**Comment by Veykril** [comment]
I think I prefer the `.cargo/config.toml` approach, our heuristic should work fine for most usages of the lib, and where it breaks its a simple one line addition to the `config.toml` to get around the heuristic.

**Comment by fasterthanlime** [comment]
Follow-up RA PR: https://github.com/rust-lang/rust-analyzer/pull/12817
